// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

#include "pensando_stats.h"

// clang-format off
const StatTable_t kPensandoStatTable = {
    // Default (32): frames_rx_* and octets_rx_* (20), frames_tx_* and octets_tx_* (11),
    // frames_tx_truncated. Verified present on all 9 ports, b36-2 (kernel 6.14).
    {"frames_rx_ok", StatTier_t::Default},
    {"frames_rx_all", StatTier_t::Default},
    {"frames_rx_bad_fcs", StatTier_t::Default},
    {"frames_rx_bad_all", StatTier_t::Default},
    {"octets_rx_ok", StatTier_t::Default},
    {"octets_rx_all", StatTier_t::Default},
    {"frames_rx_unicast", StatTier_t::Default},
    {"frames_rx_multicast", StatTier_t::Default},
    {"frames_rx_broadcast", StatTier_t::Default},
    {"frames_rx_pause", StatTier_t::Default},
    {"frames_rx_bad_length", StatTier_t::Default},
    {"frames_rx_undersized", StatTier_t::Default},
    {"frames_rx_oversized", StatTier_t::Default},
    {"frames_rx_fragments", StatTier_t::Default},
    {"frames_rx_jabber", StatTier_t::Default},
    {"frames_rx_pripause", StatTier_t::Default},
    {"frames_rx_stomped_crc", StatTier_t::Default},
    {"frames_rx_too_long", StatTier_t::Default},
    {"frames_rx_vlan_good", StatTier_t::Default},
    {"frames_rx_dropped", StatTier_t::Default},
    {"frames_tx_ok", StatTier_t::Default},
    {"frames_tx_all", StatTier_t::Default},
    {"frames_tx_bad", StatTier_t::Default},
    {"octets_tx_ok", StatTier_t::Default},
    {"octets_tx_total", StatTier_t::Default},
    {"frames_tx_unicast", StatTier_t::Default},
    {"frames_tx_multicast", StatTier_t::Default},
    {"frames_tx_broadcast", StatTier_t::Default},
    {"frames_tx_pause", StatTier_t::Default},
    {"frames_tx_pripause", StatTier_t::Default},
    {"frames_tx_vlan", StatTier_t::Default},
    {"frames_tx_truncated", StatTier_t::Default},

    // Extended: RX size buckets + frames_rx_other (12)
    {"frames_rx_less_than_64b", StatTier_t::Extended},
    {"frames_rx_64b", StatTier_t::Extended},
    {"frames_rx_65b_127b", StatTier_t::Extended},
    {"frames_rx_128b_255b", StatTier_t::Extended},
    {"frames_rx_256b_511b", StatTier_t::Extended},
    {"frames_rx_512b_1023b", StatTier_t::Extended},
    {"frames_rx_1024b_1518b", StatTier_t::Extended},
    {"frames_rx_1519b_2047b", StatTier_t::Extended},
    {"frames_rx_2048b_4095b", StatTier_t::Extended},
    {"frames_rx_4096b_8191b", StatTier_t::Extended},
    {"frames_rx_8192b_9215b", StatTier_t::Extended},
    {"frames_rx_other", StatTier_t::Extended},

    // Extended: TX size buckets + frames_tx_other + frames_tx_pri_0..7 (20)
    {"frames_tx_less_than_64b", StatTier_t::Extended},
    {"frames_tx_64b", StatTier_t::Extended},
    {"frames_tx_65b_127b", StatTier_t::Extended},
    {"frames_tx_128b_255b", StatTier_t::Extended},
    {"frames_tx_256b_511b", StatTier_t::Extended},
    {"frames_tx_512b_1023b", StatTier_t::Extended},
    {"frames_tx_1024b_1518b", StatTier_t::Extended},
    {"frames_tx_1519b_2047b", StatTier_t::Extended},
    {"frames_tx_2048b_4095b", StatTier_t::Extended},
    {"frames_tx_4096b_8191b", StatTier_t::Extended},
    {"frames_tx_8192b_9215b", StatTier_t::Extended},
    {"frames_tx_other", StatTier_t::Extended},
    {"frames_tx_pri_0", StatTier_t::Extended},
    {"frames_tx_pri_1", StatTier_t::Extended},
    {"frames_tx_pri_2", StatTier_t::Extended},
    {"frames_tx_pri_3", StatTier_t::Extended},
    {"frames_tx_pri_4", StatTier_t::Extended},
    {"frames_tx_pri_5", StatTier_t::Extended},
    {"frames_tx_pri_6", StatTier_t::Extended},
    {"frames_tx_pri_7", StatTier_t::Extended},

    // Extended: frames_rx_pri_0..7 (8)
    {"frames_rx_pri_0", StatTier_t::Extended},
    {"frames_rx_pri_1", StatTier_t::Extended},
    {"frames_rx_pri_2", StatTier_t::Extended},
    {"frames_rx_pri_3", StatTier_t::Extended},
    {"frames_rx_pri_4", StatTier_t::Extended},
    {"frames_rx_pri_5", StatTier_t::Extended},
    {"frames_rx_pri_6", StatTier_t::Extended},
    {"frames_rx_pri_7", StatTier_t::Extended},

    // Extended: pripause 1us counters + rx_pause_1us_count (17)
    {"tx_pripause_0_1us_count", StatTier_t::Extended},
    {"tx_pripause_1_1us_count", StatTier_t::Extended},
    {"tx_pripause_2_1us_count", StatTier_t::Extended},
    {"tx_pripause_3_1us_count", StatTier_t::Extended},
    {"tx_pripause_4_1us_count", StatTier_t::Extended},
    {"tx_pripause_5_1us_count", StatTier_t::Extended},
    {"tx_pripause_6_1us_count", StatTier_t::Extended},
    {"tx_pripause_7_1us_count", StatTier_t::Extended},
    {"rx_pripause_0_1us_count", StatTier_t::Extended},
    {"rx_pripause_1_1us_count", StatTier_t::Extended},
    {"rx_pripause_2_1us_count", StatTier_t::Extended},
    {"rx_pripause_3_1us_count", StatTier_t::Extended},
    {"rx_pripause_4_1us_count", StatTier_t::Extended},
    {"rx_pripause_5_1us_count", StatTier_t::Extended},
    {"rx_pripause_6_1us_count", StatTier_t::Extended},
    {"rx_pripause_7_1us_count", StatTier_t::Extended},
    {"rx_pause_1us_count", StatTier_t::Extended},

    // Extended: FEC (3), from netlink FEC stats, not ethtool -S.
    {"corrected_blocks", StatTier_t::Extended},
    {"uncorrectable_blocks", StatTier_t::Extended},
    {"corrected_bits", StatTier_t::Extended},

    // Extended: FEC symbol-error histogram (16), kernel 6.18+ only. Present in
    // the table so they surface automatically once the netlink handler grows
    // histogram support (see netlink_ethtool.cpp fec_stats_handler comment);
    // absent (not "N/A") on every kernel tested so far.
    {"fec_symbols_err_0", StatTier_t::Extended},
    {"fec_symbols_err_1", StatTier_t::Extended},
    {"fec_symbols_err_2", StatTier_t::Extended},
    {"fec_symbols_err_3", StatTier_t::Extended},
    {"fec_symbols_err_4", StatTier_t::Extended},
    {"fec_symbols_err_5", StatTier_t::Extended},
    {"fec_symbols_err_6", StatTier_t::Extended},
    {"fec_symbols_err_7", StatTier_t::Extended},
    {"fec_symbols_err_8", StatTier_t::Extended},
    {"fec_symbols_err_9", StatTier_t::Extended},
    {"fec_symbols_err_10", StatTier_t::Extended},
    {"fec_symbols_err_11", StatTier_t::Extended},
    {"fec_symbols_err_12", StatTier_t::Extended},
    {"fec_symbols_err_13", StatTier_t::Extended},
    {"fec_symbols_err_14", StatTier_t::Extended},
    {"fec_symbols_err_15", StatTier_t::Extended},
};
// clang-format on
